<?xml version="1.0" encoding="UTF-8"?>
<MobileElementEntity>
   <description></description>
   <name>Go to Login Page</name>
   <tag></tag>
   <elementGuidId>c41da8a6-c106-4787-8c53-9af69336a341</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <locator>com.Advantage.aShopping:id/textViewMenuUser</locator>
   <locatorCollection>
      <entry>
         <key>ATTRIBUTES</key>
      </entry>
      <entry>
         <key>CLASS_NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>NAME</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_VIEWTAG</key>
         <value></value>
      </entry>
      <entry>
         <key>CUSTOM</key>
         <value></value>
      </entry>
      <entry>
         <key>ID</key>
         <value></value>
      </entry>
      <entry>
         <key>ACCESSIBILITY</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_PREDICATE_STRING</key>
         <value></value>
      </entry>
      <entry>
         <key>IOS_CLASS_CHAIN</key>
         <value></value>
      </entry>
      <entry>
         <key>ANDROID_UI_AUTOMATOR</key>
         <value>new UiSelector()</value>
      </entry>
   </locatorCollection>
   <locatorStrategy>ID</locatorStrategy>
   <platform>ANDROID</platform>
</MobileElementEntity>
